services:
  next-caching-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: next-caching-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - db-caching

  next-caching-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: next-caching-backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db-caching
  db-caching:
    image: postgres:14
    container_name: db-caching
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-caching
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin-caching:
    image: dpage/pgadmin4
    container_name: pgadmin-caching
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db-caching
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data: